<footer class="footer" role="contentinfo">
	<div class="footer__row promotion-logos">
		<h6 class="promotion-logos__title">This promotion is brought to you by:</h6>
		<ul class="promotion-logos__list">
			<li class="promotion-logos__item"><a href="http://zerodegreeswest.com/" target="_blank"><img src="dst/images/zero-degrees-west.png" alt="Zero Degrees West"></a></li>
			<li class="promotion-logos__item"><a href="http://www.primalscreen.tv/" target="_blank"><img src="dst/images/primal-screen.png" alt="Primal Screen"></a></li>
			<li class="promotion-logos__item"><a href="http://www.hasbrostudios.com/" target="_blank"><img src="dst/images/hasbro-studios.png" alt="Hasbro Studios"></a></li>
			<li class="promotion-logos__item"><a href="http://bristolbronies.co.uk/" target="_blank"><img src="dst/images/bristol-bronies.png" alt="Bristol Bronies"></a></li>
		</ul>
	</div>
	<div class="footer__row footer__row--legal">
		<p><small><strong>TERMS &amp; CONDITIONS:</strong> Entries close at 11:59pm BST on 14th June 2015. Entry is open to residents of the United Kingdom (England, Scotland, Wales, Northern Ireland) only, excluding employees of the promoter, its agents, or anyone professionally associated with the promotion. One entry per person. No entries from agents, third parties, organised groups or entries automatically generated by computer will be accepted. Winners will be selected at random within five working days of the closing date and notified within 14 working days. The prizes are not transferable or exchangeable and cannot be redeemed for cash or any other form of compensation. The winners agree to comply with the reasonable requests of the promoter and its agents. We reserve the right to publish the names of the prize winners; and the right to verify all entries including but not limited to asking for address and identity details and to refuse to award a prize or withdraw prize entitlement and/or refuse further participation in the promotion and disqualify the participant where there are reasonable grounds to believe there has been a breach of these terms and conditions. These terms and conditions are governed by English Law and shall be subject to the exclusive jurisdiction of the English and Welsh Courts.</small></p>
		<p><small>For more information about this giveaway, contact <strong>Holly Windsor, Zero Degrees West, 22 Stukeley Street, London WC2B 5LR</strong> or call <strong>020 7462 0400</strong>.</small></p>
		<p><small>My Little Pony: Friendship is Magic is &copy; Hasbro. Bristol Bronies is not affiliated in any way with Hasbro or DHX Media. No copyright infringement intended.</small></p>
		<p><small>HASBRO and its logo, MY LITTLE PONY: FRIENDSHIP IS MAGIC and all related logos and characters are trademarks of Hasbro and are used with permission. &copy; 2012, 2013 Hasbro. All Rights Reserved.</small></p>
	</div>
</footer>