<?php 
	require "partials/_html-header.php";
	require "partials/_header.php";
?>

<div class="grid">

	<article class="legal">
		<header class="legal__header">
			<h1 class="legal__title">Terms &amp; Conditions</h1>
		</header>
		<div class="content legal__body">
			<p>Entries close at 11:59pm BST on 14th June 2015. Entry is open to residents of the United Kingdom (England, Scotland, Wales, Northern Ireland) only, excluding employees of the promoter, its agents, or anyone professionally associated with the promotion. One entry per person. No entries from agents, third parties, organised groups or entries automatically generated by computer will be accepted. Winners will be selected at random within five working days of the closing date and notified within 14 working days. The prizes are not transferable or exchangeable and cannot be redeemed for cash or any other form of compensation. The winners agree to comply with the reasonable requests of the promoter and its agents. We reserve the right to publish the names of the prize winners; and the right to verify all entries including but not limited to asking for address and identity details and to refuse to award a prize or withdraw prize entitlement and/or refuse further participation in the promotion and disqualify the participant where there are reasonable grounds to believe there has been a breach of these terms and conditions. These terms and conditions are governed by English Law and shall be subject to the exclusive jurisdiction of the English and Welsh Courts.</p>
		</div>
	</article>

</div>

<?php 
	require "partials/_footer.php";
	require "partials/_html-footer.php";
?>